USE project;


-- query 1
INSERT OVERWRITE LOCAL DIRECTORY 'output/eda/q1'
ROW FORMAT DELIMITED 
FIELDS TERMINATED BY ','

SELECT genres, COUNT(*) 
FROM movies
GROUP BY genres
LIMIT 15;


-- query 2
INSERT OVERWRITE LOCAL DIRECTORY 'output/eda/q1'
ROW FORMAT DELIMITED 
FIELDS TERMINATED BY ','
